version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tasks
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build: ./docker/php
    container_name: php_tasks
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_tasks
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  node:
    image: node:20
    container_name: node_tasks
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"] # <-- hace que el contenedor arranque React y no se cierre

volumes:
  mysql_data:
